config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :schedules

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :schedules
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @title = "Planning Tool"
        if current_user.present?
            redirect_to schedules_path
        end
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /schedules or /schedules.json
  def index
    @schedules = current_user.schedules
    # @schedules = Schedule.all
  end
  

  # GET /schedules/1 or /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules or /schedules.json
  def create
    @schedule = Schedule.new(schedule_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to schedule_url(@schedule), notice: "Schedule was successfully created." }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1 or /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to schedule_url(@schedule), notice: "Schedule was successfully updated." }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1 or /schedules/1.json
  def destroy
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url, notice: "Schedule was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def schedule_params
      params.require(:schedule).permit(:start_date, :project_details, :task_assigned, :task_status, :deadline, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/home/index.html.erb
<h2><%= @title %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Planning-Tool</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'schedules/header' %>
      <div class="container">
        <div class="row">
          <%# <p class= "notice"><%= notice %></p>
          <%# <p class= "alert"><%= alert %></p>  
          <%= yield %>
        </div>
      </div>
    <%= render 'schedules/footer' %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

  </body>
</html>

app/views/schedules/_edit.html.erb
<div class="container">
  <h1>Editing schedule</h1>

  <%= render "form", schedule: @schedule %>

  <br>

  <div>
    <%= link_to "Show this schedule", @schedule %> |
    <%= link_to "Back to schedules", schedules_path %>
  </div>
</div>

app/views/schedules/_footer.html.erb
<div class="b-example-divider"></div>

<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
    <p class="text-center text-body-secondary">© 2023 Company, Inc</p>
    
   
  </footer>

</div>

app/views/schedules/_form.html.erb
<div class="container">
  <%= form_with(model: schedule) do |form| %>
    <% if schedule.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

        <ul>
          <% schedule.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div class="col-lg-3">
    <div class="form-group">
      <%= form.label :start_date, style: "display: block",class: 'mb-2' %>
      <%= form.date_field :start_date, class: 'form-control form-control-lg rounded-0' %>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="form-group">
      <%= form.label :project_details, style: "display: block",class: 'mb-2' %>
      <%= form.text_field :project_details, class: 'form-control form-control-lg rounded-0' %>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="form-group">
      <%= form.label :task_assigned, style: "display: block",class: 'mb-2' %>
      <%= form.text_field :task_assigned, class: 'form-control form-control-lg rounded-0' %>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="form-group">
      <%= form.label :task_status, style: "display: block",class: 'mb-2' %>
      <%= form.text_field :task_status, class: 'form-control form-control-lg rounded-0' %>
    </div>
  </div>

  <div class="col-lg-3">
    <div class="form-group">
      <%= form.label :deadline, style: "display: block",class: 'mb-2' %>
      <%= form.date_field :deadline, class: 'form-control form-control-lg rounded-0' %>
    </div>
  </div>
  <div class="col-lg-3">
    <div><div class="form-group">
      <%= form.label :description, style: "display: block",class: 'mb-2' %>
      <%= form.text_area :description,class: 'form-control form-control-sm rounded-0' %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 mt-4">
      <%= form.submit class: "btn btn-primary btn-sm mt-2 mb-2 rounded-0" %>
      <%= link_to "Back to Schedules", schedules_path, class: "btn btn-outline_success btn-sm rounded-0" %>
    </div>
  </div>
  <% end %>
</div>

app/views/schedules/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to 'Planning Index', root_path, class: 'navbar-brand' %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home </a>
        </li>
        <li class="nav-item active">
          <% if user_signed_in? %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          <% else %>
            <%= link_to "Sign In", user_session_path, class: "nav-link" %>
          <%end%>
          
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      
      
    </div>
  </div>
</nav>

app/views/schedules/_schedule.html.erb
<div id="<%= dom_id schedule %>">


  <p>
    <strong>Start Date:</strong>
    <%= schedule.start_date %>
  </p> 
  <p>
    <strong>Project Details:</strong>
    <%= schedule.project_details %>
  </p>
  <p>
    <strong>Task Assigned:</strong>
    <%= schedule.task_assigned %>
  </p>
  <p>
    <strong>Task Status:</strong>
    <%= schedule.task_status %>
  </p>
  <p>
    <strong>Deadline:</strong>
    <%= schedule.deadline %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= schedule.description %>
  </p>  

</div>

app/views/schedules/edit.html.erb
<div class="container">
    <h1>Edit schedule</h1>

    <%= render "form", schedule: @schedule %>

    <br>
</div>

app/views/schedules/index.html.erb
<div class="container">
  <div class="col-lg-12">
    <div class="card rounded-0 mt-5 mb-5">
      <div class="card-body">
        <h2 class="text-center">Listing Schedule</h2>
      </div> 
    </div>

  <p style="color: green"><%= notice %></p>
  <%=link_to "New schedule", new_schedule_path, class: "btn btn-primary btn-sm mb-4" %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Start Date</th>
        <th>Project Details</th>
        <th>Task Assigned</th>
        <th>Status</th>
        <th>Deadline</th>
        <th>Description</th>
        <th colspan="7">Actions</th>
      </tr>
    <thead>
    <tbody>


    <div id="schedules">
      <% @schedules.each do |schedule| %>
        <tr>
          <td><%= schedule.start_date %></td>
          <td><%= schedule.project_details %></td>
          <td><%= schedule.task_assigned %></td>
          <td><%= schedule.task_status %></td>
          <td><%= schedule.deadline %></td>
          <td><%= schedule.description %></td>
          <td><%= link_to "view", schedule, class: "btn btn-info btn-sm" %></td>
          <td><%= link_to "Edit", edit_schedule_path(schedule),class: 'color;green', class: "btn btn-success btn-sm" %></td>
          <td><%= button_to "Delete", schedule, method: :delete, data: { confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>

  </table>
    
    
  </div>
</div>

 

app/views/schedules/new.html.erb
<div class="class container">
    <h1>New schedule</h1>

    <%= render "form", schedule: @schedule %>
</div>

app/views/schedules/show.html.erb
<div class="container">
  <div class="mx-* 0.5 mt-5 mb-5" style="width: 300px;">
    
      <p style="color: orange"><%= notice%></p>


      <%= render @schedule %>

      <div>
        <%= link_to "Edit this schedule", edit_schedule_path(@schedule),class: 'color;green', class: "btn btn-primary btn-sm mb-4 rounded-0" %> |
        <%= link_to "Back to schedules", schedules_path, class: "btn btn-primary btn-sm mb-4 rounded-0" %> |
        <%= button_to "Destroy this schedule", @schedule, method: :delete, class: "btn btn-danger btn-sm mb-4 rounded-0"  %>
      </div>
  </div>
</div>